"""add fx_rate model

Revision ID: 027f90bc1332
Revises: 5e3cceaade34
Create Date: 2026-07-24 09:33:46.126085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027f90bc1332'
down_revision: Union[str, Sequence[str], None] = '5e3cceaade34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fx_rates'))
    )
    op.create_index('ix_fx_rates_currency_on_date', 'fx_rates', ['currency', 'on_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fx_rates_currency_on_date', table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
