"""

Revision ID: 2a21a15e1956
Revises: 3b5cfb5e613c
Create Date: 2026-07-24 07:54:28.240757

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a21a15e1956'
down_revision: str | Sequence[str] | None = '3b5cfb5e613c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('coupon_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'],
                            ['bonds.id'],
                            name=op.f('fk_coupons_bond_id_bonds'),
                            ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons'))
    )
    op.create_index('ix_coupons_bond_id_coupon_date',
                    'coupons',
                    ['bond_id', 'coupon_date'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coupons_bond_id_coupon_date', table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
