"""

Revision ID: 3b5cfb5e613c
Revises: b19d600fc807
Create Date: 2026-07-23 08:49:44.976534

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b5cfb5e613c'
down_revision: str | Sequence[str] | None = 'b19d600fc807'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secid', sa.String(length=36), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('issuer_type',
              sa.Enum('GOVERNMENT', 'MUNICIPAL', 'CORPORATE', 'FOREIGN', name='issuertype'),
              nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('coupon_frequency', sa.Integer(), nullable=False),
    sa.Column('coupon_type',
              sa.Enum('FLOAT', 'FIXED', 'ZERO', 'VARIABLE', name='coupontype'),
              nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bonds')),
    sa.UniqueConstraint('secid', name=op.f('uq_bonds_secid'))
    )
    op.create_index(op.f('ix_bonds_maturity_date'), 'bonds', ['maturity_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bonds_maturity_date'), table_name='bonds')
    op.drop_table('bonds')

    sa.Enum(name='issuertype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='coupontype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
