"""add quote model

Revision ID: 5e3cceaade34
Revises: 2a21a15e1956
Create Date: 2026-07-24 08:55:28.811117

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e3cceaade34'
down_revision: str | Sequence[str] | None = '2a21a15e1956'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('clean_price_pct', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('accrued_interest', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'],
                            ['bonds.id'],
                            name=op.f('fk_quotes_bond_id_bonds'),
                            ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes'))
    )
    op.create_index('ix_quotes_bond_id_quote_date',
                    'quotes',
                    ['bond_id', 'quote_date'],
                    unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotes_bond_id_quote_date', table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
