"""add favorite model

Revision ID: 8449a582a67d
Revises: 027f90bc1332
Create Date: 2026-07-24 10:00:25.619605

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8449a582a67d'
down_revision: str | Sequence[str] | None = '027f90bc1332'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('added_at',
              sa.DateTime(timezone=True),
              server_default=sa.text('now()'),
              nullable=False),
    sa.ForeignKeyConstraint(['bond_id'],
                            ['bonds.id'],
                            name=op.f('fk_favorites_bond_id_bonds'),
                            ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites')),
    sa.UniqueConstraint('bond_id', name=op.f('uq_favorites_bond_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
