"""init

Revision ID: b19d600fc807
Revises: 
Create Date: 2026-06-22 14:27:12.857533

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'b19d600fc807'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
